id: REDSTONE_ORE_EXTRA
type: FEATURE

anchors:
  - &structure
    REDSTONE_ORE_SMALL: 1
  - &densityThreshold 1/256 * ${config/ore_distribution.yml:REDSTONE_ORE_EXTRA.averageCountPerChunk}
  - &salt $config/ore_distribution.yml:REDSTONE_ORE_EXTRA.salt
  - &range $config/ore_distribution.yml:REDSTONE_ORE_EXTRA.range
  - &standard-deviation (${config/ore_distribution.yml:REDSTONE_ORE_EXTRA.range.max}-${config/ore_distribution.yml:REDSTONE_ORE_EXTRA.range.min})/6
distributor:
  type: SAMPLER
  sampler:
    type: POSITIVE_WHITE_NOISE
    salt: *salt
  threshold: *densityThreshold

locator:
  type: GAUSSIAN_RANDOM
  amount: 1
  height: *range
  standard-deviation: *standard-deviation

structures:
  distribution:
    type: CONSTANT
  structures: *structure