id: AEROPELAGO
version: 0.1.0
author: Astrash

addons:
  language-yaml: 0.1.+
  chunk-generator-noise-3d: 0.1.+
  config-noise-function: 0.1.+
  palette-block-shortcut: 0.1.+
  config-biome: 0.1.+
  biome-provider-single: 0.1.+
  config-palette: 0.1.+
  config-feature: 0.1.+
  config-distributors: 0.1.+
  config-locators: 0.1.+
  structure-block-shortcut: "1.+"
  structure-terrascript-loader: "1.+"
  generation-stage-feature: "1.+"

generator: NOISE_3D

biomes:
  type: SINGLE
  biome: PLAINS

# Generation stages that come after the initial chunk generation
stages:
  - id: flora
    type: FEATURE

samplers:
  humidity:
    dimensions: 2
    type: OPEN_SIMPLEX_2
    frequency: 0.01

functions:
  lerp:
    # Linear interpolation between two values
    arguments:
      - t
      - at # Value of t where output = a
      - a
      - bt # Value of t where output = b
      - b
      # Values of t between at and bt will be interpolated
    expression: |
      if(at<bt,
        if(t<=at,a,if(t>=bt,b,a*(t-bt)/(at-bt)+b*(t-at)/(bt-at))),
        if(t>=at,a,if(t<=bt,b,a*(t-bt)/(at-bt)+b*(t-at)/(bt-at)))
      )
